owner: SegoGithub # GitHub username
repo: status.sego.app # GitHub repository name
sites: # List of endpoints to track
  - name: Main Website
    url: https://sego.app
  - name: Analytics
    url: https://analytics.sego.app
assignees: # Users to assign downtime issues (optional)
  - SegoGithub
status-website: # Status website (optional)
  cname: status.sego.app # Custom domain CNAME
  name: Upptime # Status website title
